export const data = [
    {
        id: 0,
        name: "Japhet Adjetey",
        date: "11-May-2022",
        address: "kasoa",
        amount: "1000",
        transaction: "withdrawal",
    },
    {
        id: 1,
        name: "Charllote Adjetey",
        date: "11-May-2022",
        address: "kasoa",
        amount: "2000",
        transaction: "deposit",
    },
    {
        id: 2,
        name: "Japhet Adjetey",
        date: "11-May-2022",
        address: "kasoa",
        amount: "1500",
        transaction: "withdrawal",
    },
    {
        id: 3,
        name: "Charllote Adjetey",
        date: "11-May-2022",
        address: "kasoa",
        amount: "2000",
        transaction: "deposit",
    },
    {
        id: 4,
        name: "Charllote Adjetey",
        date: "11-May-2022",
        address: "kasoa",
        amount: "2000",
        transaction: "deposit",
    },
    {
        id: 5,
        name: "Charllote Adjetey",
        date: "11-May-2022",
        address: "kasoa",
        amount: "2000",
        transaction: "deposit",
    },
    {
        id: 6,
        name: "Charllote Adjetey",
        date: "11-May-2022",
        address: "kasoa",
        amount: "2000",
        transaction: "deposit",
    },
    {
        id: 7,
        name: "Charllote Adjetey",
        date: "11-May-2022",
        address: "kasoa",
        amount: "2000",
        transaction: "deposit",
    },
    {
        id: 8,
        name: "Charllote Adjetey",
        date: "11-May-2022",
        address: "kasoa",
        amount: "2000",
        transaction: "deposit",
    },
    {
        id: 9,
        name: "Charllote Adjetey",
        date: "11-May-2022",
        address: "kasoa",
        amount: "2000",
        transaction: "deposit",
    }
]

